""
##CRIE UM PROGRAMA QUE APRESENTE UMA TABELA DO CORRESPONDÊNCIA DE MEDIDADAS DE TEMPERATURA, APRESENTANDO EM CADA O VALOR EM C E SEU EQUIVALENTE EM F. A TABELA DEVE COMEÇAR EM -10 C E TERMINAR EM 20 C. A MEDIDAS DEVEM SER APRESENTADAS EM UM INTERCALOR DE 5 EM 5.
##A FORMULA DE CONVERSÃO É: F = 1.8 * C +32

print('***TABELA DE CONVERSÃO C PARA F ***')
graus_c = -10

while graus_c <= 20:
  graus_f = 1.8 * graus_c + 32
  print(f'{graus_c:3d}°C <==> {graus_f:4.1f}°F')
  graus_c += 5
  print(graus_f)
